---
- hosts: omero-all
  roles:
    - role: ome.postgresql
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]
      postgresql_version: "10"
    - role: ome.omero_server
      omero_server_rootpassword: ChangeMe
      omero_server_release: 5.6.0-m5
      omero_server_python3: true
    - role: ome.omero_web
      omero_web_python3: true
