---

- src: ome.postgresql
  version: 3.3.1

- name: ome.omero_server
  src:
    https://github.com/ome/ansible-role-omero-server/archive/19747f05bba640df9f562fd95b1cae655ebe8e0c.tar.gz
  version: 19747f05bba640df9f562fd95b1cae655ebe8e0c

- name: ome.omero_web
  src:
    https://github.com/ome/ansible-role-omero-web/archive/c24baed1476b08b9dc49fa26f359d6b72447d81b.tar.gz
  version: c24baed1476b08b9dc49fa26f359d6b72447d81b
