---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-all
    image: leandelivery/docker-systemd:ubuntu-18.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: test-dependencies.yml
    converge: ../../playbook-ubuntu.yml
  inventory:
    host_vars:
      omero-all:
        omero_server_systemd_require_network: false
scenario:
  name: ubuntu1804
verifier:
  name: testinfra
  lint:
    name: flake8
